---

- hosts: mac
  roles:
    - role: mac
      tags: mac

- hosts: dev
  roles:
    - role: development
      tags: development


- hosts: mercy
  roles:
    - role: mercy
      tags: mercy

- hosts: centurylink
  roles:
    - role: centurylink
      tags: centurylink
