---

## Install and configure prerequisites for Monitoring team.

- name: Install Docker
  homebrew:
    name: docker

- name: Install Vagrant
  homebrew_cask:
    name: vagrant

- name: Install Ansible
  homebrew:
    name: ansible

- name: Install RSync
  homebrew:
    name: rsync

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

# We'll need MySQL to compile the Ruby `mysql` gem.
- name: Install MySQL
  homebrew:
    name: mysql

- name: Add Vagrant host names to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.* {{ item.hostname }}$'
    line: "{{ item.ip_address }}  {{ item.hostname }}"
  with_items:
    - { hostname: watcher1.local, ip_address: 192.168.99.91 }
    - { hostname: watcher2.local, ip_address: 192.168.99.92 }
    - { hostname: watcher3.local, ip_address: 192.168.99.93 }
    - { hostname: watcher4.local, ip_address: 192.168.99.94 }
    - { hostname: watcher5.local, ip_address: 192.168.99.95 }
  become: true
