---

## Install and configure prerequisites for Monitoring team.

# Note that this is Hashicorp's Vault. Ansible comes with a separate/different `ansible-vault`.
- name: Install Vault
  homebrew:
    name: vault

- name: Install Docker
  homebrew:
    name: docker

- name: Install Vagrant
  homebrew_cask:
    name: vagrant

- name: Determine installed Vagrant plugins
  command: vagrant plugin list
  register: vagrant_plugins
  changed_when: FALSE

- name: Install Vagrant plugins that we use
  command: "vagrant plugin install {{ item }}"
  when: "item not in vagrant_plugins.stdout"
  with_items:
    - vagrant-vbguest
    - vagrant-omnibus
    - vagrant-berkshelf

- name: Install Chef Development Kit
  homebrew_cask:
    name: chefdk

- name: Install Ansible
  homebrew:
    name: ansible

- name: Install RSync
  homebrew:
    name: rsync

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

# We'll need MySQL to compile the Ruby `mysql` gem.
- name: Install MySQL
  homebrew:
    name: mysql

- name: Add Vagrant host names to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.* {{ item.hostname }}$'
    line: "{{ item.ip_address }}  {{ item.hostname }}"
  with_items:
    - { hostname: watcher1, ip_address: 192.168.99.91 }
    - { hostname: watcher2, ip_address: 192.168.99.92 }
    - { hostname: watcher3, ip_address: 192.168.99.93 }
    - { hostname: watcher4, ip_address: 192.168.99.94 }
    - { hostname: watcher5, ip_address: 192.168.99.95 }
  become: true

- name: Install Tunnelblick
  homebrew_cask:
    name: tunnelblick

- name: Install Microsoft Remote Desktop
  shell: mas install $(mas search 'Microsoft Remote Desktop' | grep ' Microsoft Remote Desktop$' | cut -f1 -d' ')
  args:
    creates: /Applications/Microsoft Remote Desktop.app
