---

# TODO: Split this out into separate handler files, once https://github.com/ansible/ansible/issues/13485 is resolved.


- name: Restart Finder
  command: killall Finder

- name: Reload QuickLook daemon
  command: qlmanage -r
