---

- debug:
    msg: Configuring Mac Finder

- name: Show all files in Finder
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Show file extensions in Finder
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: When opening a new Finder window, start in the home directory
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    value: "file://{{ ansible_env.HOME }}"
  notify:
    - Restart Finder

- name: Allow quitting Finder
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: TRUE
    type: bool
  notify:
    - Restart Finder

- name: Disable animations in Finder
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    value: TRUE
    type: bool

- name: Disable animations when opening a QuickLook window
  osx_defaults:
    domain: NSGlobalDomain
    key: QLPanelAnimationDuration
    value: 0
    type: float
