---

- debug:
    msg: Configuring Mac Finder

- name: Allow quitting Finder
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: TRUE
    type: bool
  notify:
    - Restart Finder
