---

# TODO:
#   * Change "TRUE" to TRUE once https://github.com/ansible/ansible-modules-extras/issues/709 is fixed.


- debug:
    msg: Configuring Mac Finder

- name: Allow quitting Finder
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: "TRUE"
    type: bool
  notify:
    - Restart Finder
