---

- name: Disable transparency in the menu bar
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleEnableMenuBarTransparency
    value: FALSE
    type: bool
  notify:
    - Restart SystemUIServer

- name: Show battery percentage charged
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    value: "YES"
  notify:
    - Restart SystemUIServer

# System Preferences > Date & Time > Clock
# Time options: Digital
- name: Set date display to digital
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: IsAnalog
    value: FALSE
    type: bool
  notify:
    - Restart SystemUIServer

# System Preferences > Date & Time > Clock
# Time options: Display the time with seconds: off
# Date options: Show the day of the week: on
# Date options: Show date: off
- name: Set date display format
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    value: "EEE h:mm"
  notify:
    - Restart SystemUIServer

- name: Determine whether Notification Center UI is running
  shell: launchctl list | grep 'com\.apple\.notificationcenterui\.agent'
  register: notification_center_ui
  ignore_errors: TRUE
  changed_when: FALSE

- name: Disable Notification Center UI
  command: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
  notify:
    - Restart SystemUIServer
  when: notification_center_ui.rc == 0
