---

- name: Install Ansible
  homebrew:
    name: ansible

- name: Install Vagrant
  homebrew_cask:
    name: vagrant

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

- name: Install Terraform
  homebrew:
    name: terraform

- name: Install Terraform Inventory
  homebrew:
    name: https://raw.github.com/adammck/terraform-inventory/master/homebrew/terraform-inventory.rb
